{{- range $name, $data := .Values.secrets }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $name }}
  labels:
    {{- include "ext-secret.labels" $ | nindent 4 }}
data:
  {{- range $k, $v := $data }}
    {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}
{{- end }}
